# @format

version: '3.9'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: ['./wait.sh']
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
